window.DDD_GAMES = [
  {
    slug: "shadows-over-florence",
    title: "Shadows Over Florence",
    system: "D&D 5e",
    type: "One-shot · Level 3",
    when: "Friday · 7:00 PM",
    venue: "Partner restaurant",
    venuePostalCode: "29501",
    seats: "2 seats left",
    style: "High roleplay · Medium combat",
    joinMode: "Instant join",
    duration: "About 4 hours",
    tableCulture: "Heroic fantasy · No PvP · New players welcome",
    gmTrust: "Experienced host · Strong reliability history",
    accessibility: "Public venue · Accessible entrance",
    tags: ["Beginner Friendly", "Verified Venue"]
  },
  {
    slug: "lighthouse-at-blackwater",
    title: "The Lighthouse at Blackwater",
    system: "Call of Cthulhu",
    type: "Mystery one-shot",
    when: "Saturday · 6:30 PM",
    venue: "Local brewery",
    venuePostalCode: "29505",
    seats: "3 seats left",
    style: "Mystery · Investigation · Horror",
    joinMode: "Request to join",
    duration: "About 4 hours",
    tableCulture: "18+ horror · Mature themes · Boundaries reviewed first",
    gmTrust: "12 games hosted · 96% would play again",
    accessibility: "Public venue · Alcohol served",
    tags: ["18+", "Public Venue"]
  },
  {
    slug: "trouble-below-the-old-road",
    title: "Trouble Below the Old Road",
    system: "Pathfinder 2e",
    type: "Learn-to-play",
    when: "Sunday · 2:00 PM",
    venue: "Community game space",
    venuePostalCode: "29506",
    seats: "4 seats left",
    style: "Beginner focused · Tactical combat",
    joinMode: "Instant join",
    duration: "About 3 hours",
    tableCulture: "Teaching table · No experience required · Characters provided",
    gmTrust: "Beginner-friendly host · Reliable attendee record",
    accessibility: "Community venue · Quiet gaming area",
    tags: ["New Players Welcome", "Characters Provided"]
  }
];
